import { BaseApi } from '@/types/apis'
import { BaseEntityPageType } from '@/types/base'
import { Result, ResultPage } from '@/types/base/response'
import { BlogContentType } from '@/types/entity/blog/content'
import { LabelTableResq } from '@/types/apis/blog/labelType'
import { BlogCategoryVO } from '@/types/apis/blog/category'
