spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型  useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/single_blog_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://localhost:27017/blog


## mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


## upload config
upload:
  rootDir: D:/project/mine/java-project
  uploadDir: /upload
  requestMappingPath: /upload/**
  moduleImagePath: /image
  moduleBlogPath: /blog